# Generated by Django 5.2.15 on 2026-06-24 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedTelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('telegram_user_id', models.BigIntegerField(unique=True, verbose_name='ID do Telegram')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='username')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='último acesso')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_telegram', to=settings.AUTH_USER_MODEL, verbose_name='usuário Django')),
            ],
            options={
                'verbose_name': 'usuário autorizado do Telegram',
                'verbose_name_plural': 'usuários autorizados do Telegram',
                'ordering': ['name'],
            },
        ),
    ]
