# Generated by Django 5.2.15 on 2026-06-24 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparties', '0003_budgetitem'),
        ('documents', '0001_initial'),
        ('payments', '0002_payment_payment_amount_cannot_be_negative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('telegram_user_id', models.BigIntegerField(db_index=True, verbose_name='ID do usuário no Telegram')),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='nome do remetente')),
                ('sender_username', models.CharField(blank=True, max_length=255, verbose_name='username do remetente')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='ativo', max_length=20, verbose_name='status')),
                ('text_content', models.TextField(blank=True, verbose_name='texto acumulado')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='valor')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='data de pagamento')),
                ('work_item_index', models.CharField(blank=True, max_length=80, verbose_name='índice etapa/item')),
                ('payment_method', models.CharField(blank=True, max_length=80, verbose_name='forma de pagamento')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='confiança')),
                ('needs_ai', models.BooleanField(default=False, verbose_name='precisa de IA')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='dados brutos')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_drafts', to='counterparties.category', verbose_name='categoria')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_drafts', to='counterparties.costcenter', verbose_name='centro de custo')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_drafts', to='counterparties.counterparty', verbose_name='fornecedor/trabalhador')),
                ('finalized_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_telegram_drafts', to='payments.payment', verbose_name='lançamento finalizado')),
                ('uploaded_files', models.ManyToManyField(blank=True, related_name='telegram_drafts', to='documents.uploadedfile', verbose_name='arquivos recebidos')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_drafts', to='counterparties.work', verbose_name='obra')),
            ],
            options={
                'verbose_name': 'rascunho do Telegram',
                'verbose_name_plural': 'rascunhos do Telegram',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['telegram_user_id', 'status'], name='telegrambot_telegra_9f67d4_idx'), models.Index(fields=['status'], name='telegrambot_status_fcecb8_idx')],
            },
        ),
    ]
