# Generated by Django 5.2.15 on 2026-06-24 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('file', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='arquivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='nome original')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='tipo de conteúdo')),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='tamanho em bytes')),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='SHA-256')),
                ('source', models.CharField(choices=[('telegram', 'Telegram'), ('manual', 'Manual'), ('ofx', 'OFX'), ('importacao', 'Importação'), ('historico', 'Histórico')], default='manual', max_length=30, verbose_name='origem')),
                ('kind', models.CharField(choices=[('comprovante', 'Comprovante'), ('ofx', 'OFX'), ('planilha', 'Planilha'), ('pdf', 'PDF'), ('imagem', 'Imagem'), ('texto', 'Texto'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='tipo')),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('processado', 'Processado'), ('erro', 'Erro'), ('ignorado', 'Ignorado')], default='recebido', max_length=30, verbose_name='status')),
                ('telegram_file_id', models.CharField(blank=True, max_length=255, verbose_name='ID do arquivo no Telegram')),
                ('telegram_message_id', models.CharField(blank=True, max_length=100, verbose_name='ID da mensagem no Telegram')),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID do usuário no Telegram')),
                ('extracted_text', models.TextField(blank=True, verbose_name='texto extraído')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'arquivo recebido',
                'verbose_name_plural': 'arquivos recebidos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'kind'], name='documents_u_source_0bf4ec_idx'), models.Index(fields=['status'], name='documents_u_status_c675db_idx'), models.Index(fields=['telegram_user_id'], name='documents_u_telegra_b8e839_idx')],
            },
        ),
    ]
