# Generated by Django 5.2.15 on 2026-06-24 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparties', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('competence_date', models.DateField(blank=True, null=True, verbose_name='data de competência')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='data de vencimento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='data de pagamento')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='número do documento')),
                ('payment_method', models.CharField(blank=True, max_length=80, verbose_name='forma de pagamento')),
                ('payer', models.CharField(blank=True, max_length=120, verbose_name='quem paga')),
                ('bank_account', models.CharField(blank=True, max_length=160, verbose_name='conta bancária')),
                ('work_item_index', models.CharField(blank=True, max_length=80, verbose_name='índice etapa/item')),
                ('source', models.CharField(choices=[('historico', 'Histórico'), ('ofx', 'OFX'), ('telegram', 'Telegram'), ('manual', 'Manual'), ('ia', 'IA'), ('importacao', 'Importação')], default='telegram', max_length=30, verbose_name='origem')),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('processando', 'Processando'), ('pendente_cadastro', 'Pendente de cadastro'), ('pendente_confirmacao', 'Pendente de confirmação'), ('corrigindo', 'Corrigindo'), ('aprovado', 'Aprovado'), ('cancelado', 'Cancelado'), ('lancado', 'Lançado'), ('conciliado', 'Conciliado'), ('possivel_duplicado', 'Possível duplicado'), ('erro', 'Erro'), ('ignorado', 'Ignorado')], default='recebido', max_length=40, verbose_name='status')),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='confiança')),
                ('needs_review', models.BooleanField(default=True, verbose_name='precisa de revisão')),
                ('review_reason', models.TextField(blank=True, verbose_name='motivo da revisão')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmado em')),
                ('user_action', models.CharField(blank=True, choices=[('aprovar', 'Aprovar'), ('corrigir', 'Corrigir'), ('cancelar', 'Cancelar')], max_length=20, verbose_name='ação do usuário')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='dados brutos')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='counterparties.category', verbose_name='categoria')),
                ('chart_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='counterparties.chartofaccount', verbose_name='plano de contas')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL, verbose_name='confirmado por')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='counterparties.costcenter', verbose_name='centro de custo')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='counterparties.counterparty', verbose_name='fornecedor/trabalhador')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('uploaded_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='documents.uploadedfile', verbose_name='arquivo de origem')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='counterparties.work', verbose_name='obra')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID do usuário no Telegram')),
                ('action', models.CharField(choices=[('aprovar', 'Aprovar'), ('corrigir', 'Corrigir'), ('cancelar', 'Cancelar')], max_length=20, verbose_name='ação')),
                ('message', models.TextField(blank=True, verbose_name='mensagem')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='dados')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='payments.payment', verbose_name='pagamento')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'confirmação de pagamento',
                'verbose_name_plural': 'confirmações de pagamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['source'], name='payments_pa_source_5efb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_pa_payment_1d6e55_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['document_number'], name='payments_pa_documen_27f286_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['work', 'work_item_index'], name='payments_pa_work_id_3052be_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentconfirmation',
            index=models.Index(fields=['action'], name='payments_pa_action_ca62f6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentconfirmation',
            index=models.Index(fields=['telegram_user_id'], name='payments_pa_telegra_a2f756_idx'),
        ),
    ]
