# Generated by Django 5.2.15 on 2026-06-24 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('gerado', 'Gerado'), ('erro', 'Erro')], default='pendente', max_length=30, verbose_name='status')),
                ('template_path', models.CharField(blank=True, max_length=255, verbose_name='modelo usado')),
                ('file', models.FileField(blank=True, upload_to='generated/payments/%Y/%m/', verbose_name='planilha gerada')),
                ('records_count', models.PositiveIntegerField(default=0, verbose_name='quantidade de registros')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='gerado em')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_export_batches', to=settings.AUTH_USER_MODEL, verbose_name='gerado por')),
                ('payments', models.ManyToManyField(blank=True, related_name='export_batches', to='payments.payment', verbose_name='pagamentos')),
            ],
            options={
                'verbose_name': 'lote de exportação',
                'verbose_name_plural': 'lotes de exportação',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='exports_exp_status_dd5d9a_idx'), models.Index(fields=['generated_at'], name='exports_exp_generat_ea9655_idx')],
            },
        ),
    ]
