# Generated by Django 5.2.15 on 2026-06-24 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0002_exportbatch_accounting_file_and_import_file'),
        ('payments', '0003_alter_payment_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exportbatch',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='fim do período'),
        ),
        migrations.AddField(
            model_name='exportbatch',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='início do período'),
        ),
        migrations.AddIndex(
            model_name='exportbatch',
            index=models.Index(fields=['period_start', 'period_end'], name='exports_exp_period__ba739f_idx'),
        ),
    ]
