# Generated by Django 5.2.15 on 2026-06-24 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nome')),
                ('normalized_name', models.CharField(max_length=150, unique=True, verbose_name='nome normalizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nome')),
                ('normalized_name', models.CharField(max_length=150, unique=True, verbose_name='nome normalizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'plano de contas',
                'verbose_name_plural': 'planos de contas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nome')),
                ('normalized_name', models.CharField(max_length=150, unique=True, verbose_name='nome normalizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'centro de custo',
                'verbose_name_plural': 'centros de custo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('normalized_name', models.CharField(max_length=200, unique=True, verbose_name='nome normalizado')),
                ('city', models.CharField(blank=True, max_length=150, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='estado')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pausada', 'Pausada'), ('concluida', 'Concluída')], default='ativa', max_length=20, verbose_name='status')),
                ('aliases', models.TextField(blank=True, verbose_name='apelidos')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'obra',
                'verbose_name_plural': 'obras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='nome principal')),
                ('normalized_name', models.CharField(db_index=True, max_length=255, verbose_name='nome normalizado')),
                ('kind', models.CharField(choices=[('fornecedor', 'Fornecedor'), ('trabalhador', 'Trabalhador'), ('cliente', 'Cliente'), ('banco', 'Banco'), ('imposto', 'Imposto/Taxa'), ('orgao_publico', 'Órgão público'), ('socio', 'Sócio/Administrador'), ('outro', 'Outro')], default='fornecedor', max_length=30, verbose_name='tipo')),
                ('person_type', models.CharField(choices=[('fisica', 'Pessoa Física'), ('juridica', 'Pessoa Jurídica'), ('desconhecida', 'Desconhecida')], default='desconhecida', max_length=20, verbose_name='tipo de pessoa')),
                ('primary_document', models.CharField(blank=True, db_index=True, max_length=14, verbose_name='CPF/CNPJ principal')),
                ('source', models.CharField(choices=[('historico', 'Histórico'), ('ofx', 'OFX'), ('telegram', 'Telegram'), ('manual', 'Manual'), ('ia', 'IA'), ('importacao', 'Importação')], default='manual', max_length=30, verbose_name='origem')),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='confiança')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('default_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_counterparties', to='counterparties.category', verbose_name='categoria padrão')),
                ('default_chart_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_counterparties', to='counterparties.chartofaccount', verbose_name='plano de contas padrão')),
                ('default_cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_counterparties', to='counterparties.costcenter', verbose_name='centro de custo padrão')),
                ('default_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_counterparties', to='counterparties.work', verbose_name='obra padrão')),
            ],
            options={
                'verbose_name': 'contraparte',
                'verbose_name_plural': 'contrapartes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CounterpartyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('document_type', models.CharField(choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('mascarado', 'Mascarado'), ('outro', 'Outro')], max_length=20, verbose_name='tipo')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='número')),
                ('source', models.CharField(choices=[('historico', 'Histórico'), ('ofx', 'OFX'), ('telegram', 'Telegram'), ('manual', 'Manual'), ('ia', 'IA'), ('importacao', 'Importação')], default='manual', max_length=30, verbose_name='origem')),
                ('confidence', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='confiança')),
                ('is_primary', models.BooleanField(default=False, verbose_name='principal')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='counterparties.counterparty', verbose_name='contraparte')),
            ],
            options={
                'verbose_name': 'documento da contraparte',
                'verbose_name_plural': 'documentos da contraparte',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='CounterpartyAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('normalized_name', models.CharField(db_index=True, max_length=255, verbose_name='nome normalizado')),
                ('source', models.CharField(choices=[('historico', 'Histórico'), ('ofx', 'OFX'), ('telegram', 'Telegram'), ('manual', 'Manual'), ('ia', 'IA'), ('importacao', 'Importação')], default='manual', max_length=30, verbose_name='origem')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='counterparties.counterparty', verbose_name='contraparte')),
            ],
            options={
                'verbose_name': 'alias da contraparte',
                'verbose_name_plural': 'aliases da contraparte',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('counterparty', 'normalized_name'), name='unique_alias_per_counterparty')],
            },
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['normalized_name'], name='counterpart_normali_5074fd_idx'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['primary_document'], name='counterpart_primary_3976e5_idx'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['kind', 'person_type'], name='counterpart_kind_23679c_idx'),
        ),
    ]
