# Generated by Django 5.2.15 on 2026-06-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='counterparty',
            constraint=models.UniqueConstraint(condition=models.Q(('primary_document', ''), _negated=True), fields=('primary_document',), name='unique_counterparty_primary_document'),
        ),
        migrations.AddConstraint(
            model_name='counterparty',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='counterparty_confidence_between_0_and_1'),
        ),
        migrations.AddConstraint(
            model_name='counterpartydocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('counterparty',), name='unique_primary_document_per_counterparty'),
        ),
        migrations.AddConstraint(
            model_name='counterpartydocument',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='counterparty_document_confidence_between_0_and_1'),
        ),
    ]
