# Generated by Django 5.2.15 on 2026-06-24 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0002_counterparty_unique_counterparty_primary_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('index', models.CharField(max_length=80, verbose_name='índice')),
                ('parent_index', models.CharField(blank=True, max_length=80, verbose_name='índice pai')),
                ('item_type', models.CharField(choices=[('etapa', 'Etapa'), ('subetapa', 'Subetapa'), ('item', 'Item'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='tipo')),
                ('code', models.CharField(blank=True, max_length=80, verbose_name='código')),
                ('base', models.CharField(blank=True, max_length=120, verbose_name='base')),
                ('service_type', models.CharField(blank=True, max_length=120, verbose_name='tipo de serviço')),
                ('description', models.TextField(verbose_name='descrição')),
                ('normalized_description', models.TextField(verbose_name='descrição normalizada')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='unidade')),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='quantidade')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='custo unitário')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='custo total')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='arquivo de origem')),
                ('source_row', models.PositiveIntegerField(blank=True, null=True, verbose_name='linha de origem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='counterparties.work', verbose_name='obra')),
            ],
            options={
                'verbose_name': 'item de orçamento',
                'verbose_name_plural': 'itens de orçamento',
                'ordering': ['work__name', 'index'],
                'indexes': [models.Index(fields=['work', 'index'], name='counterpart_work_id_62e98b_idx'), models.Index(fields=['work', 'item_type'], name='counterpart_work_id_c8b486_idx'), models.Index(fields=['parent_index'], name='counterpart_parent__14103b_idx')],
                'constraints': [models.UniqueConstraint(fields=('work', 'index'), name='unique_budget_item_per_work_index')],
            },
        ),
    ]
