# Generated by Django 5.2.15 on 2026-06-27 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0003_budgetitem'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('processado', 'Processado'), ('erro', 'Erro')], default='processado', max_length=30, verbose_name='status')),
                ('rows_read', models.PositiveIntegerField(default=0, verbose_name='linhas lidas')),
                ('rows_skipped', models.PositiveIntegerField(default=0, verbose_name='linhas ignoradas')),
                ('items_created', models.PositiveIntegerField(default=0, verbose_name='itens criados')),
                ('items_updated', models.PositiveIntegerField(default=0, verbose_name='itens atualizados')),
                ('items_unchanged', models.PositiveIntegerField(default=0, verbose_name='itens sem alteração')),
                ('conflicts', models.JSONField(blank=True, default=list, verbose_name='conflitos')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='importado por')),
                ('uploaded_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_import_batches', to='documents.uploadedfile', verbose_name='arquivo importado')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_import_batches', to='counterparties.work', verbose_name='obra')),
            ],
            options={
                'verbose_name': 'importação de orçamento',
                'verbose_name_plural': 'importações de orçamento',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['work', 'status'], name='counterpart_work_id_ea2a26_idx'), models.Index(fields=['created_at'], name='counterpart_created_d806d5_idx')],
            },
        ),
    ]
