# Generated by Django 5.2.15 on 2026-06-24 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparties', '0001_initial'),
        ('documents', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfxFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('original_filename', models.CharField(max_length=255, verbose_name='nome original')),
                ('bank_id', models.CharField(blank=True, max_length=50, verbose_name='banco')),
                ('account_id', models.CharField(blank=True, max_length=80, verbose_name='conta')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='data inicial')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='data final')),
                ('status', models.CharField(choices=[('importado', 'Importado'), ('processado', 'Processado'), ('erro', 'Erro'), ('ignorado', 'Ignorado')], default='importado', max_length=30, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_ofx_files', to=settings.AUTH_USER_MODEL, verbose_name='importado por')),
                ('uploaded_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofx_file', to='documents.uploadedfile', verbose_name='arquivo recebido')),
            ],
            options={
                'verbose_name': 'arquivo OFX',
                'verbose_name_plural': 'arquivos OFX',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('fitid', models.CharField(max_length=120, verbose_name='FITID')),
                ('transaction_type', models.CharField(blank=True, max_length=30, verbose_name='tipo')),
                ('posted_at', models.DateField(verbose_name='data')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor')),
                ('memo', models.TextField(blank=True, verbose_name='memo/histórico')),
                ('normalized_memo', models.TextField(blank=True, verbose_name='memo normalizado')),
                ('document_extracted', models.CharField(blank=True, max_length=32, verbose_name='CPF/CNPJ extraído')),
                ('name_extracted', models.CharField(blank=True, max_length=255, verbose_name='nome extraído')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('conciliada', 'Conciliada'), ('possivel_duplicada', 'Possível duplicada'), ('sem_lancamento', 'Sem lançamento'), ('divergente', 'Divergente'), ('ignorada', 'Ignorada')], default='pendente', max_length=40, verbose_name='status')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='dados brutos')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofx_transactions', to='counterparties.counterparty', verbose_name='contraparte')),
                ('ofx_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.ofxfile', verbose_name='arquivo OFX')),
            ],
            options={
                'verbose_name': 'transação OFX',
                'verbose_name_plural': 'transações OFX',
                'ordering': ['-posted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('sugerida', 'Sugerida'), ('confirmada', 'Confirmada'), ('rejeitada', 'Rejeitada')], default='sugerida', max_length=30, verbose_name='status')),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='confiança')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reconciliations', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='payments.payment', verbose_name='pagamento')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='banking.ofxtransaction', verbose_name='transação OFX')),
            ],
            options={
                'verbose_name': 'conciliação',
                'verbose_name_plural': 'conciliações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ofxfile',
            index=models.Index(fields=['bank_id', 'account_id'], name='banking_ofx_bank_id_6d72c6_idx'),
        ),
        migrations.AddIndex(
            model_name='ofxfile',
            index=models.Index(fields=['status'], name='banking_ofx_status_f650ff_idx'),
        ),
        migrations.AddIndex(
            model_name='ofxtransaction',
            index=models.Index(fields=['posted_at'], name='banking_ofx_posted__ffb602_idx'),
        ),
        migrations.AddIndex(
            model_name='ofxtransaction',
            index=models.Index(fields=['amount'], name='banking_ofx_amount_15cba0_idx'),
        ),
        migrations.AddIndex(
            model_name='ofxtransaction',
            index=models.Index(fields=['status'], name='banking_ofx_status_f2da7e_idx'),
        ),
        migrations.AddIndex(
            model_name='ofxtransaction',
            index=models.Index(fields=['document_extracted'], name='banking_ofx_documen_36e744_idx'),
        ),
        migrations.AddConstraint(
            model_name='ofxtransaction',
            constraint=models.UniqueConstraint(fields=('ofx_file', 'fitid'), name='unique_fitid_per_ofx_file'),
        ),
        migrations.AddIndex(
            model_name='reconciliation',
            index=models.Index(fields=['status'], name='banking_rec_status_94da3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliation',
            constraint=models.UniqueConstraint(fields=('payment', 'transaction'), name='unique_payment_transaction'),
        ),
    ]
