# Generated by Django 5.2.15 on 2026-06-24 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        ('counterparties', '0002_counterparty_unique_counterparty_primary_document_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ofxtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('fitid', ''), _negated=True), name='ofx_transaction_fitid_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='reconciliation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmada')), fields=('payment',), name='unique_confirmed_reconciliation_per_payment'),
        ),
        migrations.AddConstraint(
            model_name='reconciliation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmada')), fields=('transaction',), name='unique_confirmed_reconciliation_per_transaction'),
        ),
        migrations.AddConstraint(
            model_name='reconciliation',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='reconciliation_confidence_between_0_and_1'),
        ),
    ]
